### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4796: character maps to <undefined>

### ISSUE THREAD

**Issue by Michael-E-Rose** [deanmalmgren/textract#164]
I am trying to parse [this](http://www.bis.org/review/R140910A.pdf) pdf file.

```
>>> pdf = "R140910A.pdf"
>>> text = textract.process(pdf).upper()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/__init__.py", line 58, in process
    return parser.process(filename, encoding, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/utils.py", line 46, in process
    unicode_string = self.decode(byte_string)
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/utils.py", line 65, in decode
    return text.decode(result['encoding'])
  File "/usr/lib/python3.5/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4796: character maps to <undefined>
>>> import chardet
>>> chardet.__version__
'3.0.4'
```

As suggested in #133 and #107, I tried chardet 2.1.1.  I get another error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/__init__.py", line 58, in process
    return parser.process(filename, encoding, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/utils.py", line 46, in process
    unicode_string = self.decode(byte_string)
  File "/usr/local/lib/python3.5/dist-packages/textract/parsers/utils.py", line 64, in decode
    result = chardet.detect(text)
  File "/usr/local/lib/python3.5/dist-packages/chardet/__init__.py", line 21, in detect
    import universaldetector
ImportError: No module named 'universaldetector'
```

That's probably a bug in their repo, because it should `from chardet.universaldetector import UniversalDetector`.  But it shows: 2.1.1 does not solve the issue.

**Comment by vitormorales** [comment]
I've got same error "UnicodeDecodeError: 'charmap' codec can't decode byte" trying parse [http://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?data=14/10/2014&jornal=1&pagina=3](url)

**Comment by deanmalmgren** [comment]
I recently started using pyup-bot to track dependency version changes. It looks like https://github.com/chardet/chardet/issues/98 is fixed now in `chardet` and, according to pyup-bot and PR #166, chardet 3.0.4 is passing all tests. 

@vitormorales's file is working with chardet 3.0.4 :tada:

@Michael-E-Rose's `R140910A.pdf` file and is still causing errors, but a different one now:

```
vagrant@dev:/vagrant$ textract R140910A.pdf 
Traceback (most recent call last):
  File "/vagrant/bin/textract", line 32, in <module>
    main()
  File "/vagrant/bin/textract", line 25, in main
    output = process(**vars(args))
  File "/vagrant/textract/parsers/__init__.py", line 77, in process
    return parser.process(filename, encoding, **kwargs)
  File "/vagrant/textract/parsers/utils.py", line 47, in process
    unicode_string = self.decode(byte_string)
  File "/vagrant/textract/parsers/utils.py", line 65, in decode
    return text.decode(result['encoding'])
  File "/usr/lib/python2.7/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4796: character maps to <undefined>
``` 
Digging into chardet a bit, it appears that chardet is not terribly confident in the encoding:
```
{
    'confidence': 0.5739492570454361, 
    'language': 'Turkish', 
    'encoding': 'Windows-1254'
}
```
Do you know what the encoding should be? This might be a good test case for `chardet` and a good place to file the issue.

**Comment by Michael-E-Rose** [comment]
The language should certainly be English, and the encoding probably `latin1`.  I have no idea why it's being detected as Turkish.

I'm happy to file an issue with chardet, but please tell me: How did you get the detection result?

**Comment by deanmalmgren** [comment]
Huh. Filing the issue with chardet will definitely be good. I know that the maintainer was actively working on some major revisions and test cases are helpful.

For debugging, I added a `print` statement [here](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/utils.py#L63-L65) like this:

```python
        # use chardet to automatically detect the encoding text
        result = chardet.detect(text)
        print result
        return text.decode(result['encoding'])
```

**Comment by Michael-E-Rose** [comment]
Sorry if I have to ask again: What exactly happens after
```
>>> import textract
>>> pdf = "R140910A.pdf"
```
so that I get the result above? Because with `result = chardet.detect(text)`, I'd have to use a string object and not a filename.

**Comment by deanmalmgren** [comment]
You have to edit the textract source code directly using the instructions above. Does that make sense?

**Comment by arevuzDisaitek** [comment]
Hello, this issue is still here. Is there something a can do to solve the problem now?

**Comment by MatthewScholefield** [comment]
Hi, this is still an issue on certain PDFs even with `chardet==3.0.4`. Is there a way to force a certain encoding? (Maybe by making a child of the pdf parser class and passing an instance of it in `extension=`)

**Comment by nateGeorge** [comment]
I have found chardet to not work well, and UnicodeDammit from beautifulsoup4 works much better. chardet seems to return 'unknown' a whole lot and UnicodeDammit seems to get it correct.

**Comment by nateGeorge** [comment]
It also seems like the `encoding` argument in process() is ignored.

**Comment by endolith** [comment]
So this means the text file is valid UTF8 but textract is incorrectly reading it as "charmap" default windows encoding?
