### ISSUE TITLE
Update EbookLib to 0.16

### ISSUE THREAD

**Issue by Frederick888** [deanmalmgren/textract#165]
I'm experiencing issues while installing `textract` in Ubuntu 16.04 (didn't have it in Arch, it automatically installed EbookLib 0.16 for me, weird...)

```
Collecting EbookLib==0.15 (from textract)
  Using cached EbookLib-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m5c04tc3/EbookLib/setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1658: ordinal not in range(128)
```

This was fixed in EbookLib 0.16. Shall we update to 0.16 as well? I'm not sure whether it would break anything though.

**Comment by Frederick888** [comment]
Ah, solved... was running in Docker and had to change the system encoding.
