### ISSUE TITLE
Need to update dependency to EbookLib 0.16 to avoid UnicodeDecodeError

### ISSUE THREAD

**Issue by benhoyle** [deanmalmgren/textract#176]
Hello.

I'm trying to install textract and the EbookLib dependency is giving me issues in Python 3. I think this can be solved by upping the dependency to EbookLib==0.16 as per here: https://github.com/aerkalov/ebooklib/issues/104

Collecting EbookLib==0.15 (from textract)
  Downloading EbookLib-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rr3k5sh_/EbookLib/setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1658: ordinal not in range(128)

**Comment by benhoyle** [comment]
Notice this is updated on the master - pip install git+https://github.com/deanmalmgren/textract.git
