### ISSUE TITLE
pixReadStreamGif: Can't use giflib-5.1.2; suggest 5.1.1 or earlier

### ISSUE THREAD

**Issue by francesco1119** [deanmalmgren/textract#200]
Hello, 
I'm experiencing an error with `textract `recognizing `.gif`

```
Traceback (most recent call last):
  File "Pukeko.py", line 125, in <module>
    dirlist(path)
  File "Pukeko.py", line 121, in dirlist
    dirlist(i)
  File "Pukeko.py", line 121, in dirlist
    dirlist(i)
  File "Pukeko.py", line 121, in dirlist
    dirlist(i)
  File "Pukeko.py", line 121, in dirlist
    dirlist(i)
  File "Pukeko.py", line 121, in dirlist
    dirlist(i)
  File "Pukeko.py", line 107, in dirlist
    GrabInputFile = textract.process(i)
  File "/usr/local/lib/python3.5/dist-packages/textract-1.6.1-py3.5.egg/textract/parsers/__init__.py", line 77, in process
    return parser.process(filename, encoding, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/textract-1.6.1-py3.5.egg/textract/parsers/utils.py", line 46, in process
    byte_string = self.extract(filename, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/textract-1.6.1-py3.5.egg/textract/parsers/image.py", line 20, in extract
    stdout, _ = self.run(args)
  File "/usr/local/lib/python3.5/dist-packages/textract-1.6.1-py3.5.egg/textract/parsers/utils.py", line 101, in run
    ' '.join(args), pipe.returncode, stdout, stderr,
textract.exceptions.ShellError: The command `tesseract ./pygobject-master/examples/demo/demos/data/floppybuddy.gif stdout` failed with exit code 1
------------- stdout -------------
b''------------- stderr -------------
b"Warning in pixReadMemGif: writing to a temp file, not directly to memory\nError in pixReadStreamGif: Can't use giflib-5.1.2; suggest 5.1.1 or earlier\nError in pixReadStream: gif: no pix returned\nError in pixRead: pix not read\nError in pixReadMemGif: pix not read\nError in pixReadMem: gif: no pix returned\nError during processing.\n"
```

This is the image

![floppybuddy](https://user-images.githubusercontent.com/3397477/35211806-da3834ae-ffbc-11e7-9fa7-65333b7f6d92.gif)

I have to say that it's not the first time I encounter problems with your library. I mean, I like `textract`, I just don't want to keep flagging you problems. 
Don't you just have a setup.py that just do the job? 

Thank you

**Comment by francesco1119** [comment]
FYI
if `tesseract-ocr` is what I need to read gifs I indeed have it:
`tesseract-ocr is already the newest version (3.04.01-4).`

**Comment by jpweytjens** [comment]
The error message states that the error is comming from tesseract, not textract. Please keep in mind that textract is only a wrapper around other tools that do the actual parsing of the file.

Tesseract is throwing this error
```
Error in pixReadStreamGif: Can't use giflib-5.1.2; suggest 5.1.1 or earlier.
```
but it seems to be fixed in an [update](https://github.com/DanBloomberg/leptonica/issues/301).

Closing this as this issue is related to tesseract.
