### ISSUE TITLE
 file named [[ text.doc ]] does not appear to really be a .doc file

### ISSUE THREAD

**Issue by kadir-calvid** [deanmalmgren/textract#208]
Hello,

I found the below error while working on .doc extension. for other file is working properly.

please provide some solution on the same.

Thanks

Error: file named [[ 1519297735038_ANUBHAV CV.doc ]] does not appear to really be a .doc file
    at ChildProcess.exithandler (child_process.js:279:5)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:568:12)

**Comment by jpweytjens** [comment]
Can you provide the file `1519297735038_ANUBHAV CV.doc` in order to investigate this issue?

**Comment by jpweytjens** [comment]
I'm closing this issue due to inactivity. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.
