### ISSUE TITLE
image to text failed code 127

### ISSUE THREAD

**Issue by saravananpsg** [deanmalmgren/textract#215]
Hi Dean,

On windows machine, I am trying to retrieve text from the jpg, png and I am getting the following error. Already, I have installed tesseract-ocr as well.  Kindly let me know how to resolve this error.

---------------------
Traceback (most recent call last):
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\textract\parsers\utils.py", line 84, in run
   stdout=subprocess.PIPE, stderr=subprocess.PIPE,
 File "C:\Users\Saravanan\Anaconda3\lib\subprocess.py", line 707, in __init__
   restore_signals, start_new_session)
 File "C:\Users\Saravanan\Anaconda3\lib\subprocess.py", line 990, in _execute_child
   startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
   exec(code_obj, self.user_global_ns, self.user_ns)
 File "<ipython-input-32-0e93f7a52f58>", line 4, in <module>
   text = textract.process(file, language='eng')
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\textract\parsers\__init__.py", line 77, in process
   return parser.process(filename, encoding, **kwargs)
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\textract\parsers\utils.py", line 46, in process
   byte_string = self.extract(filename, **kwargs)
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\textract\parsers\image.py", line 20, in extract
   stdout, _ = self.run(args)
 File "C:\Users\Saravanan\Anaconda3\lib\site-packages\textract\parsers\utils.py", line 91, in run
   ' '.join(args), 127, '', '',
textract.exceptions.ShellError: The command `tesseract C:/Users/Saravanan/Downloads/Text Extraction/jpgtext.jpg stdout -l eng` failed with exit code 127
------------- stdout -------------
------------- stderr -------------

**Comment by saravananpsg** [comment]
Just found out the issue. After adding the directory path in the environment variable for Tesseract-OCR, I can able to use the image to string function.
Please close this issue

**Comment by dataxienxe** [comment]
Hi, 

I'm having this exact same issue. Can you please explain to me how you solved it? I'm still getting error exit code 127. 
How did you specify the path to tesseract?

**Comment by jpweytjens** [comment]
Can you provide the full error log? Error code 127 means that the command line tool textract uses to parse your full can not be found. Generally, this means that it is not installed or is not visible in the environment that textract is running.

What kind of file are you trying to process? You can check here which tool textract is using to parse this file. If it is installed, make sure the (virtual) environment that you're using has a path variable with the directory in which the tool is installed.
