### ISSUE TITLE
Getting " failed with exit code 127" on windows 10.

### ISSUE THREAD

**Issue by arsalan993** [deanmalmgren/textract#229]
I have heard from different sources this error is associated with windows 10 . 
`textract.exceptions.ShellError: The command `pdftotext ../data/input/example_resumes\Brendan_Herger_Resume.pdf -` failed with exit code 127
------------- stdout -------------
------------- stderr -------------`

But still i cant find any solution. 
Please help
my system specs are Python 2.7 and Windows 10.

**Comment by armiro** [comment]
I'm on windows 8, running python 3.6. Also getting the same error. Installed poppler pdf2text.exe but the error is still here.

**Comment by shenoi** [comment]
i too get the same error. the specification is windows 8 and python 2.7

**Comment by RajaParikshit** [comment]
I'm facing same problem

**Comment by y-tee** [comment]
File not found error and shell error

```---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in run(self, args)
     83                 args,
---> 84                 stdout=subprocess.PIPE, stderr=subprocess.PIPE,
     85             )

~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:

~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

ShellError                                Traceback (most recent call last)
<ipython-input-9-9f62837da01d> in <module>()
----> 1 text=textract.process('C:/Users/ytdon/Desktop/your pet project/lalalaa.pdf',method='pdftotext')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\__init__.py in process(filename, encoding, extension, **kwargs)
     75 
     76     parser = filetype_module.Parser()
---> 77     return parser.process(filename, encoding, **kwargs)
     78 
     79 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in process(self, filename, encoding, **kwargs)
     44         # output encoding
     45         # http://nedbatchelder.com/text/unipain/unipain.html#35
---> 46         byte_string = self.extract(filename, **kwargs)
     47         unicode_string = self.decode(byte_string)
     48         return self.encode(unicode_string, encoding)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
     26                     return self.extract_pdfminer(filename, **kwargs)
     27                 else:
---> 28                     raise ex
     29 
     30         elif method == 'pdfminer':

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
     18         if method == '' or method == 'pdftotext':
     19             try:
---> 20                 return self.extract_pdftotext(filename, **kwargs)
     21             except ShellError as ex:
     22                 # If pdftotext isn't installed and the pdftotext method

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract_pdftotext(self, filename, **kwargs)
     41         else:
     42             args = ['pdftotext', filename, '-']
---> 43         stdout, _ = self.run(args)
     44         return stdout
     45 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in run(self, args)
     89                 # This is equivalent to getting exitcode 127 from sh
     90                 raise exceptions.ShellError(
---> 91                     ' '.join(args), 127, '', '',
     92                 )
     93 

ShellError: The command `pdftotext C:/Users/ytdon/Desktop/your pet project/lalalaa.pdf -` failed with exit code 127
------------- stdout -------------
------------- stderr -------------```

**Comment by ewerkema** [comment]
After a little bit of research I found out that the text extractors were working in a BASH environment, but not from the Windows command line. For me these text extractors were located at `C:\Program Files\Git\mingw64\bin` and by adding this to my PATH variables I solved the errors.

**Comment by marcelo-dalmeida** [comment]
> File not found error and shell error
> 
> ```
> FileNotFoundError                         Traceback (most recent call last)
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in run(self, args)
>      83                 args,
> ---> 84                 stdout=subprocess.PIPE, stderr=subprocess.PIPE,
>      85             )
> 
> ~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
>     708                                 errread, errwrite,
> --> 709                                 restore_signals, start_new_session)
>     710         except:
> 
> ~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
>     996                                          os.fspath(cwd) if cwd is not None else None,
> --> 997                                          startupinfo)
>     998             finally:
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> ShellError                                Traceback (most recent call last)
> <ipython-input-9-9f62837da01d> in <module>()
> ----> 1 text=textract.process('C:/Users/ytdon/Desktop/your pet project/lalalaa.pdf',method='pdftotext')
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\__init__.py in process(filename, encoding, extension, **kwargs)
>      75 
>      76     parser = filetype_module.Parser()
> ---> 77     return parser.process(filename, encoding, **kwargs)
>      78 
>      79 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in process(self, filename, encoding, **kwargs)
>      44         # output encoding
>      45         # http://nedbatchelder.com/text/unipain/unipain.html#35
> ---> 46         byte_string = self.extract(filename, **kwargs)
>      47         unicode_string = self.decode(byte_string)
>      48         return self.encode(unicode_string, encoding)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
>      26                     return self.extract_pdfminer(filename, **kwargs)
>      27                 else:
> ---> 28                     raise ex
>      29 
>      30         elif method == 'pdfminer':
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
>      18         if method == '' or method == 'pdftotext':
>      19             try:
> ---> 20                 return self.extract_pdftotext(filename, **kwargs)
>      21             except ShellError as ex:
>      22                 # If pdftotext isn't installed and the pdftotext method
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\pdf_parser.py in extract_pdftotext(self, filename, **kwargs)
>      41         else:
>      42             args = ['pdftotext', filename, '-']
> ---> 43         stdout, _ = self.run(args)
>      44         return stdout
>      45 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\textract-1.6.1-py3.6.egg\textract\parsers\utils.py in run(self, args)
>      89                 # This is equivalent to getting exitcode 127 from sh
>      90                 raise exceptions.ShellError(
> ---> 91                     ' '.join(args), 127, '', '',
>      92                 )
>      93 
> 
> ShellError: The command `pdftotext C:/Users/ytdon/Desktop/your pet project/lalalaa.pdf -` failed with exit code 127
> ------------- stdout -------------
> ------------- stderr -------------```
> ```

The error above was appearing to me after downloading and setting the as system path variable (C:\antiword).

The error disappeared after restarting the computer

**Comment by jpweytjens** [comment]
Can you try textract `1.6.2`? This update should have fixed this issue. See also #26

**Comment by jpweytjens** [comment]
I'm closing this issue due to inactivity. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.

**Comment by navneet-arya** [comment]
> I'm closing this issue due to inactivity. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.

Hi

I am using textract version 1.6.3 but still I am getting this error on Window 10.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\utils.py in run(self, args)
     83                 args,
---> 84                 stdout=subprocess.PIPE, stderr=subprocess.PIPE,
     85             )

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1177                                          os.fspath(cwd) if cwd is not None else None,
-> 1178                                          startupinfo)
   1179             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

ShellError                                Traceback (most recent call last)
<ipython-input-16-00c227a0c87f> in <module>
----> 1 f=tt.process('db.pdf')

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\__init__.py in process(filename, encoding, extension, **kwargs)
     75 
     76     parser = filetype_module.Parser()
---> 77     return parser.process(filename, encoding, **kwargs)
     78 
     79 

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\utils.py in process(self, filename, encoding, **kwargs)
     44         # output encoding
     45         # http://nedbatchelder.com/text/unipain/unipain.html#35
---> 46         byte_string = self.extract(filename, **kwargs)
     47         unicode_string = self.decode(byte_string)
     48         return self.encode(unicode_string, encoding)

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
     26                     return self.extract_pdfminer(filename, **kwargs)
     27                 else:
---> 28                     raise ex
     29 
     30         elif method == 'pdfminer':

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\pdf_parser.py in extract(self, filename, method, **kwargs)
     18         if method == '' or method == 'pdftotext':
     19             try:
---> 20                 return self.extract_pdftotext(filename, **kwargs)
     21             except ShellError as ex:
     22                 # If pdftotext isn't installed and the pdftotext method

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\pdf_parser.py in extract_pdftotext(self, filename, **kwargs)
     41         else:
     42             args = ['pdftotext', filename, '-']
---> 43         stdout, _ = self.run(args)
     44         return stdout
     45 

c:\users\navneet.a.arya\appdata\local\programs\python\python37\lib\site-packages\textract\parsers\utils.py in run(self, args)
     89                 # This is equivalent to getting exitcode 127 from sh
     90                 raise exceptions.ShellError(
---> 91                     ' '.join(args), 127, '', '',
     92                 )
     93 

ShellError: The command `pdftotext db.pdf -` failed with exit code 127
------------- stdout -------------
------------- stderr -------------

**Comment by gitak47** [comment]
> 
> 
> I'm closing this issue due to inactivity. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.

Still does not work

**Comment by maxiuboldi** [comment]
> I'm closing this issue due to inactivity. If you still encounter the issue with the latest version of textract, feel free to leave a comment with additional information and I'll reopen the issue.

Does not work.

**Comment by frantz2501** [comment]
same here!

**Comment by HiromitsuHarada** [comment]
It seems an OS error. The PC couldn't pipe to 'pdftotext'.
If you used the cmd in Windows PC, let's try to use a bash type console like git bash to execute a command 'python ***.py'.

**Comment by bluetyson** [comment]
Yes, currently the same.

**Comment by SSJenny90** [comment]
For those working with .doc filetypes, antiword doesn't work if there are spaces in your FULL file path. Removing spaces in the file path fixed all issues for me.

**Comment by Danble** [comment]
Hello! As @ewerkema said this extractor doesn't work in windows shells. It needs a bash terminal.
I faced and solve the problem using git bash.
In order to do that, go to your working directory using git bash and type:
(assuming you're using a virtual environment )
`cd Scripts` and press enter.
now type `. activate` With this you will inside your virtualenv.
And that's all, now you can run your program on windows without this issue.

**Comment by bluetyson** [comment]
So activate the environment again, inside git bash?

**Comment by jjcasalo** [comment]
Hi,
Same problem here.
Environement :
 - Windows 10 Pro
 - Using the Wing IDE
 - DOC files are in folder path without spaces (C:\temp\SimilarTexts\)

**Comment by shrikantpadhy18** [comment]
> I have heard from different sources this error is associated with windows 10 .
> `textract.exceptions.ShellError: The command `pdftotext ../data/input/example_resumes\Brendan_Herger_Resume.pdf -` failed with exit code 127 ------------- stdout ------------- ------------- stderr -------------`
> 
> But still i cant find any solution.
> Please help
> my system specs are Python 2.7 and Windows 10.

How did u got rid of this error ? I  am using windows 10

**Comment by gadjetnut** [comment]
I am having this problem too. Windows 10. Textract version 1.6.4. I've included the error message and all the installed packages with version below.

Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\utils.py", line 87, in run
    pipe = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 
951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 
1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:      

Traceback (most recent call last):
  File "c:\Users\User1\Google Drive\Python\ResumeScanner\pdf.py", line 3, in <module>
    text = textract.process(file, method='pdfminer')
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\__init__.py", line 79, in process
    return parser.process(filename, input_encoding, output_encoding, **kwargs)
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\utils.py", line 46, in process
    byte_string = self.extract(filename, **kwargs)
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\pdf_parser.py", line 32, in extract
    return self.extract_pdfminer(filename, **kwargs)
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\pdf_parser.py", line 54, in extract_pdfminer
    stdout, _ = self.run(['pdf2txt.py', filename])
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\textract\parsers\utils.py", line 95, in run
    raise exceptions.ShellError(
textract.exceptions.ShellError: The command `pdf2txt.py ./resume.pdf` failed with exit code 127
------------- stdout -------------
------------- stderr -------------
Package                 Version
----------------------- -----------
absl-py                 0.13.0
anyascii                0.3.0
argcomplete             1.10.3
astunparse              1.6.3
beautifulsoup4          4.8.2
cachetools              4.2.2
certifi                 2021.5.30
chardet                 3.0.4
charset-normalizer      2.0.4
clang                   5.0
compressed-rtf          1.0.6
cycler                  0.10.0
docx2txt                0.8
ebcdic                  1.1.1
EbookLib                0.17.1
extract-msg             0.28.7
flatbuffers             1.12
gast                    0.4.0
google-auth             1.35.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.39.0
h5py                    3.1.0
idna                    3.2
IMAPClient              2.1.0
keras                   2.6.0
Keras-Preprocessing     1.1.2
kiwisolver              1.3.2
lxml                    4.7.1
Markdown                3.3.4
matplotlib              3.4.3
numpy                   1.19.5
oauthlib                3.1.1
olefile                 0.46
opt-einsum              3.3.0
pandas                  1.3.2
pdfminer.six            20191110
Pillow                  8.3.2
pip                     21.3.1
protobuf                3.17.3
pyahocorasick           1.4.2
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycryptodome            3.12.0
pyparsing               2.4.7
python-dateutil         2.8.2
python-pptx             0.6.21
pytz                    2021.1
pytz-deprecation-shim   0.1.0.post0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.7.2
six                     1.12.0
sortedcontainers        2.4.0
soupsieve               2.3.1
SpeechRecognition       3.8.1
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.6.0
tensorflow-estimator    2.6.0
termcolor               1.1.0
textract                1.6.4
textsearch              0.0.21
typing-extensions       3.7.4.3
tzdata                  2021.5
tzlocal                 4.1
urllib3                 1.26.6
Werkzeug                2.0.1
wheel                   0.37.0
wrapt                   1.12.1
xlrd                    1.2.0
XlsxWriter              3.0.2

**Comment by gadjetnut** [comment]
I resolved the problem by using WSL : https://code.visualstudio.com/docs/remote/wsl and chose the Debian environment

**Comment by jpf01** [comment]
same problem here 

in textract-1.6.5-py3-none-any.whl
w10
executing through IDLE

textract.exceptions.ShellError: The command `pdftotext ./0969389.pdf -` failed with exit code 127
textract.exceptions.ShellError: The command `pdftotext 0969389.pdf -` failed with exit code 127

**Comment by Fer-cinnamon** [comment]
Same problem, I'm trying to open a .doc file, and I can't, same error.

**Comment by omshukla11** [comment]
> After a little bit of research I found out that the text extractors were working in a BASH environment, but not from the Windows command line. For me these text extractors were located at `C:\Program Files\Git\mingw64\bin` and by adding this to my PATH variables I solved the errors.

I have a virtual environment setup can you direct me to what to do in that case please? Thank you

**Comment by nstommel-ey** [comment]
You NEED to switch to a bash shell currently to properly run textract on certain file types like pdf. I use PyCharm and this worked well for me. Use `C:\Users\<your_username_here>\AppData\Local\Programs\Git\bin\bash.exe --login` in PyCharm's terminal shell picker path.

**Comment by juangelos** [comment]
Solved by COPYING the antiword.exe file from C:\antiword\antiword.exe  to the folder of the py file.
(use case: .DOC with antiword on Windows 11 latest Insiders beta)

**Comment by zhouyang-bigdata** [comment]
> After a little bit of research I found out that the text extractors were working in a BASH environment, but not from the Windows command line. For me these text extractors were located at `C:\Program Files\Git\mingw64\bin` and by adding this to my PATH variables I solved the errors.

good. 
add C:\Program Files\Git\mingw64\bin to your environment variable path.

**Comment by wycoal** [comment]
conda install -c [conda-forge](https://so.csdn.net/so/search?q=conda-forge&spm=1001.2101.3001.7020) poppler
