### ISSUE TITLE
PDF extract failed!

### ISSUE THREAD

**Issue by Lswx2017** [deanmalmgren/textract#248]
When i extract text from a pdf, it output:
Traceback (most recent call last):
  File "/u
[1.pdf](https://github.com/deanmalmgren/textract/files/2418871/1.pdf)

sr/bin/textract", line 32, in <module>
    main()
  File "/usr/bin/textract", line 25, in main
    output = process(**vars(args))
  File "/usr/lib/python2.7/site-packages/textract/parsers/__init__.py", line 77, in process
    return parser.process(filename, encoding, **kwargs)
  File "/usr/lib/python2.7/site-packages/textract/parsers/utils.py", line 47, in process
    unicode_string = self.decode(byte_string)
  File "/usr/lib/python2.7/site-packages/textract/parsers/utils.py", line 65, in decode
    return text.decode(result['encoding'])
TypeError: decode() argument 1 must be string, not None

**Comment by matt32106** [comment]
Can you show the code you use to extract?

**Comment by mpena2099** [comment]
Same error here, but NOT for all my PDF files.

Python 3.6.5
textract==1.6.1
chardet==2.3.0

**Comment by mpena2099** [comment]
"chardet.detect(text)" (utils.py, 64) returns  {'encoding': None, 'confidence': 0.0}

**Comment by SatyaRamGV** [comment]
`text = textract.process(file, method='pdfminer')`

Error:
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-e7fe7b1fc2d1> in <module>()
----> 1 text = textract.process(file, method='pdfminer')

~/.local/lib/python3.6/site-packages/textract/parsers/__init__.py in process(filename, encoding, extension, **kwargs)
     75 
     76     parser = filetype_module.Parser()
---> 77     return parser.process(filename, encoding, **kwargs)
     78 
     79 

~/.local/lib/python3.6/site-packages/textract/parsers/utils.py in process(self, filename, encoding, **kwargs)
     44         # output encoding
     45         # http://nedbatchelder.com/text/unipain/unipain.html#35
---> 46         byte_string = self.extract(filename, **kwargs)
     47         unicode_string = self.decode(byte_string)
     48         return self.encode(unicode_string, encoding)

~/.local/lib/python3.6/site-packages/textract/parsers/pdf_parser.py in extract(self, filename, method, **kwargs)
     29 
     30         elif method == 'pdfminer':
---> 31             return self.extract_pdfminer(filename, **kwargs)
     32         elif method == 'tesseract':
     33             return self.extract_tesseract(filename, **kwargs)

~/.local/lib/python3.6/site-packages/textract/parsers/pdf_parser.py in extract_pdfminer(self, filename, **kwargs)
     46     def extract_pdfminer(self, filename, **kwargs):
     47         """Extract text from pdfs using pdfminer."""
---> 48         stdout, _ = self.run(['pdf2txt.py', filename])
     49         return stdout
     50 

~/.local/lib/python3.6/site-packages/textract/parsers/utils.py in run(self, args)
     94         # pipe.wait() ends up hanging on large files. using
     95         # pipe.communicate appears to avoid this issue
---> 96         stdout, stderr = pipe.communicate()
     97 
     98         # if pipe is busted, raise an error (unlike Fabric)

`UnboundLocalError: local variable 'pipe' referenced before assignment`

**Comment by jpweytjens** [comment]
Looks similar to #261 and #256. Could you try again with textract `1.6.2`? This version updates chardet to `3.0.4`.

**Comment by afs25** [comment]
Hi, I am hitting this error when I try to textract this PDF:
[Acta_Acustica_High_frequency_mistuning_2018.pdf](https://github.com/deanmalmgren/textract/files/3481668/Acta_Acustica_High_frequency_mistuning_2018.pdf)

I am using textract 1.6.1 (latest version available via pip install) and chardet 3.0.4.

The output of chardet on the same file is "no result":
$ chardet Acta_Acustica_High_frequency_mistuning_2018.pdf Acta_Acustica_High_frequency_mistuning_2018.pdf: no result

**Comment by jpweytjens** [comment]
@afs25 I'm aware that textract returns `bytes` objects where it should be returning `strings` instead. In the meanwhile, you can decode the textract output with the required decoding.

```
text = textract.process("Acta.pdf", method="pdfminer").decode("utf8")
```

As for the failing with `chardet`, I'm currently far away from any computer. Feel free to ping me again in 2 weeks if I haven't fixed it these issues by then.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yeshanliu** [comment]
> @afs25 I'm aware that textract returns `bytes` objects where it should be returning `strings` instead. In the meanwhile, you can decode the textract output with the required decoding.
> 
> ```
> text = textract.process("Acta.pdf", method="pdfminer").decode("utf8")
> ```
> 
> As for the failing with `chardet`, I'm currently far away from any computer. Feel free to ping me again in 2 weeks if I haven't fixed it these issues by then.
> 
> Sent with [GitHawk](http://githawk.com)
Hello,Sir. Any solution right now?

**Comment by erosennin** [comment]
With `pdftotext`, there is absolutely no need to guess the encoding with `chardet`, because `pdftotext` always outputs UTF-8, unless specified otherwise with the `-enc` option:

```
$ man pdftotext|grep -C3 UTF-8
             Generate an XHTML file containing bounding box information for each block, line, and word in the file.

       -enc encoding-name
              Sets the encoding to use for text output. This defaults to "UTF-8".

       -listenc
              Lits the available encodings
```

Please stop using `chardet` with `pdftotext` and just treat the output as valid `UTF-8`.

You users would be very thankful. :)

**Comment by Filip98** [comment]
What about other methods, e.g does pdfminer or tesseract always return utf-8?
Should we attempt to use chardet from the textract package or
```
from textract import process
from chardet import detect
text = process("file.pdf",method="tesseract",language="srp+srp_latn")
print(text.decode(detect(text)["encoding"]))
```
pdftotext works well only for simple pdf's,
pdfminer/tesseract work better for my file but neither really return correct results, don't know how I should debug tesseract as it doesn't directly support pdf's, textract uses pdftoppm, right?
Complaining here makes no sense if I can't make it work with just the tools in the background
