### ISSUE TITLE
The extension .pptx is not supported. I know ppt is not but why .pptx? In the available extensions it shows .pptx but it is not working.

### ISSUE THREAD

**Issue by anirudhpnbb** [deanmalmgren/textract#333]
I am attaching the error it is throwing

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pptx/parts/image.py", line 11, in <module>
    from PIL import Image as PIL_Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/textract/parsers/__init__.py", line 69, in process
    rel_module, 'textract.parsers'
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/textract/parsers/pptx_parser.py", line 1, in <module>
    import pptx
  File "/usr/local/lib/python3.7/dist-packages/pptx/__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "/usr/local/lib/python3.7/dist-packages/pptx/api.py", line 15, in <module>
    from .package import Package
  File "/usr/local/lib/python3.7/dist-packages/pptx/package.py", line 14, in <module>
    from .parts.image import Image, ImagePart
  File "/usr/local/lib/python3.7/dist-packages/pptx/parts/image.py", line 13, in <module>
    import Image as PIL_Image
ModuleNotFoundError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anirudh/Desktop/pdo_ext/text_process.py", line 15, in <module>
    main()
  File "/home/anirudh/Desktop/pdo_ext/text_process.py", line 8, in main
    startprocess('/home/anirudh/Desktop/new_mock')
  File "/home/anirudh/Desktop/pdo_ext/extraction.py", line 23, in extraction_process
    textex(allfiles, alltext)        # Starting the text extraction on all the files available.
  File "/home/anirudh/Desktop/pdo_ext/textext.py", line 21, in text_extraction
    output = textract.process(file_name).decode('utf-8')
  File "/usr/local/lib/python3.7/dist-packages/textract/parsers/__init__.py", line 72, in process
    raise exceptions.ExtensionNotSupported(ext)
textract.exceptions.ExtensionNotSupported: The filename extension .pptx is not yet supported by
textract. Please suggest this filename extension here:

    https://github.com/deanmalmgren/textract/issues

Available extensions include: .csv, .doc, .docx, .eml, .epub, .gif, .htm, .html, .jpeg, .jpg, .json, .log, .mp3, .msg, .odt, .ogg, .pdf, .png, .pptx, .ps, .psv, .rtf, .tff, .tif, .tiff, .tsv, .txt, .wav, .xls, .xlsx

**Comment by wajdikhattel** [comment]
Well `.pptx` is supported, but if you read carefully it says that `ModuleNotFoundError: No module named 'Image'` and this is due to that in the `textract.parsers.__init__.py` there is a try/except that tests only on importing the parser correctly and not its existance.

So basically if you install the `Image` module, this will be solved for you.
